### ISSUE TITLE
Running ./main on sample audio just hangs on CentOS 7.9

### ISSUE THREAD

**Issue by regstuff** [ggerganov/whisper.cpp#106]
I have successfully compiled and used whisper.cpp on Ubuntu 20.04. But when trying on CentOS 7.9, which comes with gcc version 4.8 by default. Whisper.cpp failed to compile with many errors.
Updated gcc to version 7 as per [here](https://superuser.com/questions/1640048/how-to-properly-upgrade-gcc-on-centos-7), but then ended up with the below error. 

```
ggml.c:217:5: warning: implicit declaration of function ‘clock_gettime’; did you mean ‘localtime’? [-Wimplicit-function-declaration]
     clock_gettime(CLOCK_MONOTONIC, &ts);
     ^~~~~~~~~~~~~
     localtime
ggml.c:217:19: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
     clock_gettime(CLOCK_MONOTONIC, &ts);
                   ^~~~~~~~~~~~~~~
ggml.c:217:19: note: each undeclared identifier is reported only once for each function it appears in
ggml.c: In function ‘ggml_time_us’:
ggml.c:223:19: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
     clock_gettime(CLOCK_MONOTONIC, &ts);
                   ^~~~~~~~~~~~~~~
make: *** [ggml.o] Error 1
```

Fixed this by compiling with this flag: `make CFLAGS=-D_POSIX_C_SOURCE=199309L` and successfully managed to compile, but then running ./main on the jfk.wav sample doesn't give any output. The screen just seems to hang after displaying the initial system_info etc. Running htop shows one thread on 100%. Changing -t to 8 or any other number doesn't change anything. All threads show 100% usage on htop. Initial output in verbose mode is below.
```
./main -m models/ggml-model-whisper-base.bin -t 1 -v samples/jfk.wav
whisper_model_load: loading model from 'models/ggml-model-whisper-base.bin'
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 2
whisper_model_load: mem_required  = 505.00 MB
whisper_model_load: adding 1608 extra tokens
whisper_model_load: ggml ctx size = 163.43 MB
whisper_model_load: memory size =    22.83 MB
whisper_model_load: model size  =   140.54 MB

system_info: n_threads = 1 / 256 | AVX2 = 0 | AVX512 = 0 | NEON = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 |

main: processing 'samples/jfk.wav' (176000 samples, 11.0 sec), 1 threads, lang = en, task = transcribe, timestamps = 1 ...
```

Not sure if this is a bug or because of older libraries. I'm not any kind of expert in builds, so I thought I'd just put this here in case anyone can suggest a way out.
Some further info about the system:
ldd (GNU libc) 2.17
The CPU is a AMD EPYC 7742
cat /proc/cpuinfo flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl xtopology nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

**Comment by ggerganov** [comment]
The output indicates that you have compiled the program without the AVX2 flags: `AVX2 = 0`
Without `AVX2`, on 1 thread the processing will take a lot of time.

Run again `make` and make sure that you see the following flags are included during the compilation: `-mavx -mavx2 -mfma -mf16c`.

Alternatively, you can do the compilation manually by running the following commands:

```bash
gcc -I.              -O3 -std=c11   -pthread -mavx -mavx2 -mfma -mf16c -D_POSIX_C_SOURCE=199309L -c ggml.c
g++ -I. -I./examples -O3 -std=c++11 -pthread -c whisper.cpp
g++ -I. -I./examples -O3 -std=c++11 -pthread examples/main/main.cpp whisper.o ggml.o -o main 
```

This should work 100%

Would be really interesting how the computation scales on this kind of CPU.

**Comment by regstuff** [comment]
@ggerganov 
The manual commands worked perfectly. Thank you.
Some quick comparisons and benchmarks on this CPU for your reference. Ran this on an audio I had lying around. (14015008 samples, 875.9 sec), 
There is some improvement from 4 to 8 threads. But when going from 8 to 128 threads, time to transcribe actually doubled! 

4 threads:
whisper_print_timings:     load time =   347.37 ms
whisper_print_timings:      mel time = 10838.96 ms
whisper_print_timings:   sample time =     0.00 ms
whisper_print_timings:   encode time = 86172.30 ms / 14362.05 ms per layer
whisper_print_timings:   decode time = 52097.71 ms / 8682.95 ms per layer
whisper_print_timings:    total time = 150048.56 ms

8 threads:
whisper_print_timings:     load time =   357.65 ms
whisper_print_timings:      mel time =  6717.11 ms
whisper_print_timings:   sample time =     0.00 ms
whisper_print_timings:   encode time = 65370.82 ms / 10895.14 ms per layer
whisper_print_timings:   decode time = 39848.97 ms / 6641.49 ms per layer
whisper_print_timings:    total time = 112892.42 ms

128 threads:
whisper_print_timings:     load time =   350.56 ms
whisper_print_timings:      mel time =   900.32 ms
whisper_print_timings:   sample time =     0.00 ms
whisper_print_timings:   encode time = 43585.14 ms / 7264.19 ms per layer
whisper_print_timings:   decode time = 219683.08 ms / 36613.85 ms per layer
whisper_print_timings:    total time = 265444.12 ms

**Comment by ggerganov** [comment]
Yes, I have observed that the computation saturates at 8 threads. My current explanation is that the computation becomes memory bound at this point and it no longer matters how much CPU power you throw at it.

It's a pity that we can't utilize so many cores! 😄

**Comment by regstuff** [comment]
@ggerganov 
I've noticed a lot of difference in the accuracy of transcription when using whisper.cpp on a regular laptop (i5-8300H quad core), and this AMD system.

Take a look at the difference in these two lines of the same audio. Both transcribed with the base model. Kept threads as 1 in both for one run, and 4 in both for another run. Accuracy difference persists,
```
i5-8300H laptop (pretty good)
[00:00:26.520 --> 00:00:36.760]   involved in Mahatma Gandhi's principles and ideals. He took part in civil disobedience
```
```
AMD CPU (quite bad)
[00:00:26.520 --> 00:00:36.760]   involved of Mah oma Gandhi's principles and ideals▒ la took back of civil disobed each
```

System info is the same for all three: `system_info: n_threads = 1 / 256 | AVX2 = 1 | AVX512 = 0 | NEON = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 |`

Funny thing is I ran whisper.cpp in a replit instance in the cloud. cat /proc/cpuinfo on the instance shows that the CPU is AMD EPYC 7B12.
make command worked just fine on it without having to do the manual stuff. The accuracy is also quite good.

Both my laptop and the replit instance are on Ubuntu 20.04.  The other AMD server is on CentOS 7.9. I think this may be the cause? 

The default gcc version on CentOS 7.9 is 4.8.5, and ./main does not run on it. Every time I login, I execute `source /opt/rh/devtoolset-7/enable` which enables gcc 7.3 before ./main can work. Wonder if this is causing the inaccuracy issue?

Regarding utilizing all the cores,.one of my requirements is to batch process a large number of files, so I wonder if I could run 16 instances of whisper with 8 threads each and get my job done 16x faster. 👍 Hopefully can figure it this inaccuracy issue.

**Comment by ggerganov** [comment]
The garbled results are strange - not sure how it could happen, but it was strange in the first place that running `make` does not automatically add the AVX flags. I also think it is something related to the OS or the compiler settings.

Regarding batch processing of multiple files, you can maybe use this idea by @vmedappa: https://github.com/ggerganov/whisper.cpp/issues/22

One potential problem is that you have to load the model in memory for each whisper instance that you launch. If you have enough RAM, then you should be good. But it is possible that the processing will again be saturated after starting some amount of instances start running together.

Alternatively, I just implemented a "parallel" option that allows you to run `P` whisper processors in single `main` process. This is the PR: https://github.com/ggerganov/whisper.cpp/pull/110. The `P` processors will share a single buffer with the model weights so it will use less memory compared to starting `P` separate instances. Currently, the strategy is to split the each provided audio file into `P` chunks and process the chunks in parallel. Initial tests indicate that for certain `P` and `T` (threads) values you can gain performance compared to using single processor. However, I am not sure how to determine the optimal `P` and `T` - it is likely to depend on the specific hardware.

Anyway, you might want to play with it and see if it helps.

I plan to add an additional option where instead of splitting each input file in `P` chunks, each processor works on a separate file. This is more close to the use case that you described and will allow you to do it with a single load of the model in memory. For example:

```
./main -m model/ggml-large.bin audio0.wav audio1.wav audio2.wav audio3.wav -p 4 -t 8
```

Hope that makes sense.

**Comment by regstuff** [comment]
The parallelization of a single audio makes sense, except of course the issue of cutting off a word where the split occurs. I guess for longer audio it may be fine.
Let me see if I can get something like Ubuntu 20.04 on the server. Might have to shuffle a lot of other things on the server to get that working.
Will keep you posted if issue persists after shifting to Ubuntu. 
Please do let me know if you have any other ideas about the bad transcription.
I'll close this issue now. Thanks for the help and this incredible package.
